import { createContext, useContext, useState, ReactNode } from "react";

type Lang = "id" | "en";

const translations: Record<Lang, Record<string, string>> = {
  id: {
    dashboard: "Dashboard",
    news: "Berita",
    categories: "Kategori Berita",
    banners: "Banner",
    menus: "Menus",
    documents: "Dokumen",
    docKinds: "Jenis Dokumen",
    docCategories: "Kategori Dokumen",
    docTypes: "Tipe File",
    permits: "Izin Penelitian",
    surveys: "Survei IKM",
    reports: "Laporan Akhir",
    suggestions: "Kotak Saran",
    templates: "Template Surat",
    users: "Manajemen User",
    bappeda: "BAPPEDA",
    rida: "RIDA",
    administration: "Administrasi",
    general: "Umum",
    logout: "Keluar",
    logoutConfirm: "Apakah Anda yakin ingin keluar dari sistem?",
    logoutTitle: "Konfirmasi Keluar",
    cancel: "Batal",
    confirm: "Ya, Keluar",
    portal: "Portal Admin BAPPERIDA Kalteng",
    save: "Simpan",
    saving: "Menyimpan...",
    edit: "Edit",
    delete: "Hapus",
    add: "Tambah",
    search: "Cari",
    name: "Nama",
    action: "Aksi",
    status: "Status",
    active: "Aktif",
    inactive: "Nonaktif",
    draft: "Draft",
    published: "Published",
    trash: "Tong Sampah",
    restore: "Pulihkan",
    previous: "Sebelumnya",
    next: "Berikutnya",
    page: "Halaman",
    of: "dari",
    loading: "Memuat...",
    noData: "Tidak ada data",
    confirmDelete: "Konfirmasi Hapus",
    confirmDeleteDesc: "Apakah Anda yakin ingin menghapus item ini? Tindakan ini tidak dapat dibatalkan.",
    create: "Buat",
    update: "Perbarui",
    close: "Tutup",
    back: "Kembali",
    preview: "Preview",
    download: "Unduh",
    generate: "Generate",
    title: "Judul",
    description: "Deskripsi",
    content: "Konten",
    date: "Tanggal",
    category: "Kategori",
    type: "Tipe",
    file: "File",
    image: "Gambar",
    role: "Peran",
    username: "Username",
    password: "Password",
    email: "Email",
    phone: "Telepon",
    address: "Alamat",
    institution: "Instansi",
    totalData: "Total data",
    searchPlaceholder: "Cari...",
    addNews: "Tambah Berita",
    editNews: "Edit Berita",
    newsTitle: "Manajemen Berita",
    newsSubtitle: "Kelola berita dan artikel BAPPERIDA",
    addCategory: "Tambah Kategori",
    editCategory: "Edit Kategori",
    categoryTitle: "Kategori Berita",
    addBanner: "Tambah Banner",
    editBanner: "Edit Banner",
    bannerTitle: "Manajemen Banner",
    addMenu: "Tambah Menu",
    editMenu: "Edit Menu",
    menuTitle: "Manajemen Menu",
    addDocument: "Tambah Dokumen",
    editDocument: "Edit Dokumen",
    documentTitle: "Manajemen Dokumen PPID",
    addUser: "Tambah User",
    editUser: "Edit User",
    userTitle: "Manajemen User",
    permitTitle: "Manajemen Izin Penelitian",
    permitSubtitle: "Kelola pengajuan izin penelitian",
    surveyTitle: "Survei IKM",
    reportTitle: "Laporan Akhir",
    suggestionTitle: "Kotak Saran",
    templateTitle: "Template Surat",
    templateSubtitle: "Kelola template surat izin penelitian",
    addTemplate: "Tambah Template",
    editTemplate: "Edit Template",
    viewDetails: "Lihat Detail",
    updateStatus: "Ubah Status",
    generateLetter: "Generate Surat",
    requestNumber: "Nomor Pengajuan",
    applicantName: "Nama Pemohon",
    researchTitle: "Judul Penelitian",
    researchLocation: "Lokasi Penelitian",
    submittedAt: "Tanggal Pengajuan",
    accessLevel: "Level Akses",
    publishYear: "Tahun Terbit",
    documentNumber: "Nomor Dokumen",
    placement: "Penempatan",
    location: "Lokasi",
    allRoles: "Semua Role",
    superAdmin: "Super Admin",
    adminBPP: "Admin BAPPEDA",
    adminRIDA: "Admin RIDA",
    filterAll: "Semua",
    filterStatus: "Filter Status",
    filterCategory: "Filter Kategori",
    noNewsFound: "Tidak ada berita ditemukan",
    noPermitFound: "Tidak ada izin penelitian ditemukan",
    noUserFound: "Tidak ada user ditemukan",
    tableColTitle: "Judul",
    tableColAuthor: "Penulis",
    tableColStatus: "Status",
    tableColDate: "Tanggal",
    tableColAction: "Aksi",
    tableColName: "Nama",
    tableColRole: "Role",
    tableColNumber: "Nomor",
    tableColApplicant: "Pemohon",
  },
  en: {
    dashboard: "Dashboard",
    news: "News",
    categories: "News Categories",
    banners: "Banners",
    menus: "Menus",
    documents: "Documents",
    docKinds: "Document Kinds",
    docCategories: "Document Categories",
    docTypes: "File Types",
    permits: "Research Permits",
    surveys: "IKM Survey",
    reports: "Final Reports",
    suggestions: "Suggestions Box",
    templates: "Letter Templates",
    users: "User Management",
    bappeda: "BAPPEDA",
    rida: "RIDA",
    administration: "Administration",
    general: "General",
    logout: "Sign Out",
    logoutConfirm: "Are you sure you want to sign out?",
    logoutTitle: "Confirm Sign Out",
    cancel: "Cancel",
    confirm: "Yes, Sign Out",
    portal: "BAPPERIDA Kalteng Admin Portal",
    save: "Save",
    saving: "Saving...",
    edit: "Edit",
    delete: "Delete",
    add: "Add",
    search: "Search",
    name: "Name",
    action: "Action",
    status: "Status",
    active: "Active",
    inactive: "Inactive",
    draft: "Draft",
    published: "Published",
    trash: "Trash",
    restore: "Restore",
    previous: "Previous",
    next: "Next",
    page: "Page",
    of: "of",
    loading: "Loading...",
    noData: "No data found",
    confirmDelete: "Confirm Delete",
    confirmDeleteDesc: "Are you sure you want to delete this item? This action cannot be undone.",
    create: "Create",
    update: "Update",
    close: "Close",
    back: "Back",
    preview: "Preview",
    download: "Download",
    generate: "Generate",
    title: "Title",
    description: "Description",
    content: "Content",
    date: "Date",
    category: "Category",
    type: "Type",
    file: "File",
    image: "Image",
    role: "Role",
    username: "Username",
    password: "Password",
    email: "Email",
    phone: "Phone",
    address: "Address",
    institution: "Institution",
    totalData: "Total records",
    searchPlaceholder: "Search...",
    addNews: "Add News",
    editNews: "Edit News",
    newsTitle: "News Management",
    newsSubtitle: "Manage BAPPERIDA news and articles",
    addCategory: "Add Category",
    editCategory: "Edit Category",
    categoryTitle: "News Categories",
    addBanner: "Add Banner",
    editBanner: "Edit Banner",
    bannerTitle: "Banner Management",
    addMenu: "Add Menu",
    editMenu: "Edit Menu",
    menuTitle: "Menu Management",
    addDocument: "Add Document",
    editDocument: "Edit Document",
    documentTitle: "PPID Document Management",
    addUser: "Add User",
    editUser: "Edit User",
    userTitle: "User Management",
    permitTitle: "Research Permit Management",
    permitSubtitle: "Manage research permit submissions",
    surveyTitle: "IKM Survey",
    reportTitle: "Final Reports",
    suggestionTitle: "Suggestions Box",
    templateTitle: "Letter Templates",
    templateSubtitle: "Manage research permit letter templates",
    addTemplate: "Add Template",
    editTemplate: "Edit Template",
    viewDetails: "View Details",
    updateStatus: "Update Status",
    generateLetter: "Generate Letter",
    requestNumber: "Request Number",
    applicantName: "Applicant Name",
    researchTitle: "Research Title",
    researchLocation: "Research Location",
    submittedAt: "Submitted At",
    accessLevel: "Access Level",
    publishYear: "Publish Year",
    documentNumber: "Document Number",
    placement: "Placement",
    location: "Location",
    allRoles: "All Roles",
    superAdmin: "Super Admin",
    adminBPP: "Admin BAPPEDA",
    adminRIDA: "Admin RIDA",
    filterAll: "All",
    filterStatus: "Filter Status",
    filterCategory: "Filter Category",
    noNewsFound: "No news found",
    noPermitFound: "No research permit found",
    noUserFound: "No user found",
    tableColTitle: "Title",
    tableColAuthor: "Author",
    tableColStatus: "Status",
    tableColDate: "Date",
    tableColAction: "Action",
    tableColName: "Name",
    tableColRole: "Role",
    tableColNumber: "Number",
    tableColApplicant: "Applicant",
  },
};

interface LangCtx {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const LangContext = createContext<LangCtx | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => (localStorage.getItem("lang") as Lang) || "id");

  const setLang = (l: Lang) => {
    localStorage.setItem("lang", l);
    setLangState(l);
  };

  const t = (key: string) => translations[lang][key] || key;

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be inside LanguageProvider");
  return ctx;
}
