import { createContext, useContext, useState, ReactNode } from "react";

type Lang = "id" | "en";

const translations: Record<Lang, Record<string, string>> = {
  id: {
    // Navigation
    dashboard: "Dashboard",
    news: "Berita",
    categories: "Kategori Berita",
    banners: "Banner",
    menus: "Menus",
    documents: "Dokumen",
    docKinds: "Jenis Dokumen",
    docCategories: "Kategori Dokumen",
    docTypes: "Tipe File",
    permits: "Izin Penelitian",
    surveys: "Survei IKM",
    reports: "Laporan Akhir",
    suggestions: "Kotak Saran",
    templates: "Template Surat",
    users: "Manajemen User",
    bappeda: "BAPPEDA",
    rida: "RIDA",
    administration: "Administrasi",
    general: "Umum",
    // Auth
    logout: "Keluar",
    logoutConfirm: "Apakah Anda yakin ingin keluar dari sistem?",
    logoutTitle: "Konfirmasi Keluar",
    portal: "Portal Admin BAPPERIDA Kalteng",
    signIn: "Masuk ke Sistem",
    signInDesc: "Gunakan akun admin yang telah diberikan",
    usernameLabel: "Username / Email",
    passwordLabel: "Password",
    loginBtn: "Masuk",
    loggingIn: "Memproses...",
    // Common
    cancel: "Batal",
    confirm: "Ya, Keluar",
    save: "Simpan",
    saving: "Menyimpan...",
    edit: "Edit",
    delete: "Hapus",
    add: "Tambah",
    search: "Cari",
    name: "Nama",
    action: "Aksi",
    status: "Status",
    active: "Aktif",
    inactive: "Nonaktif",
    draft: "Draft",
    published: "Published",
    trash: "Tong Sampah",
    restore: "Pulihkan",
    previous: "Sebelumnya",
    next: "Berikutnya",
    page: "Halaman",
    of: "dari",
    loading: "Memuat...",
    noData: "Tidak ada data",
    confirmDelete: "Konfirmasi Hapus",
    confirmDeleteDesc: "Apakah Anda yakin ingin menghapus item ini? Tindakan ini tidak dapat dibatalkan.",
    create: "Buat",
    update: "Perbarui",
    close: "Tutup",
    back: "Kembali",
    preview: "Preview",
    download: "Unduh",
    generate: "Generate",
    title: "Judul",
    description: "Deskripsi",
    content: "Konten",
    date: "Tanggal",
    category: "Kategori",
    type: "Tipe",
    file: "File",
    image: "Gambar",
    role: "Peran",
    username: "Username",
    password: "Password",
    email: "Email",
    phone: "Telepon",
    address: "Alamat",
    institution: "Instansi",
    totalData: "Total data",
    searchPlaceholder: "Cari...",
    enterTrash: "Masuk Trash",
    exitTrash: "Keluar Trash",
    // Dashboard
    welcomeBack: "Selamat datang kembali",
    totalNews: "Total Berita",
    publishedNews: "dipublikasi",
    draftNews: "Draft Berita",
    trashNews: "Berita Trash",
    activeBanners: "Banner Aktif",
    ppidDocs: "Dokumen PPID",
    researchPermits: "Izin Penelitian",
    waitingReview: "menunggu review",
    pendingReview: "Menunggu Review",
    ikmSurvey: "Survei IKM",
    avgSatisfaction: "Rata-rata Kepuasan",
    newsDocTab: "Berita & Dokumen",
    permitTab: "Izin Penelitian",
    surveyTab: "Survei Kepuasan",
    failedStats: "Gagal memuat statistik",
    fromLastMonth: "dari bulan lalu",
    // News
    addNews: "Tambah Berita",
    editNews: "Edit Berita",
    newsTitle: "Manajemen Berita",
    newsSubtitle: "Kelola berita dan artikel BAPPERIDA",
    addCategory: "Tambah Kategori",
    editCategory: "Edit Kategori",
    categoryTitle: "Kategori Berita",
    // Banner
    addBanner: "Tambah Banner",
    editBanner: "Edit Banner",
    bannerTitle: "Manajemen Banner",
    bannerSubtitle: "Kelola banner dan iklan portal",
    bannerTitleField: "Judul Banner",
    bannerAltText: "Alt Text (aksesibilitas)",
    bannerAltDesc: "Deskripsi gambar untuk screen reader...",
    bannerPlacement: "Placement",
    bannerPlacementHome: "Beranda",
    bannerPlacementNews: "Berita",
    bannerPlacementSidebar: "Sidebar",
    bannerPlacementPopup: "Popup",
    bannerLinkType: "Tipe Link",
    bannerLinkTypeExt: "External URL",
    bannerLinkTypePage: "Halaman Internal",
    bannerLinkTypeNews: "Berita",
    bannerLinkUrl: "URL Link",
    bannerDesktop: "Gambar Desktop",
    bannerMobile: "Gambar Mobile",
    bannerStartAt: "Mulai Tayang",
    bannerEndAt: "Selesai Tayang",
    bannerActivate: "Aktifkan Banner",
    bannerActivateDesc: "Banner aktif akan tampil di portal publik",
    bannerViews: "Views",
    bannerClicks: "Clicks",
    bannerStatus: "Status",
    bannerGambar: "Gambar",
    bannerJudulPlacement: "Judul & Placement",
    bannerNotFound: "Belum ada banner",
    bannerInTrash: "Tidak ada banner di trash",
    bannerDeleted: "Banner dihapus",
    bannerUpdated: "Banner diupdate",
    bannerCreated: "Banner dibuat",
    bannerSave: "Simpan Banner",
    bannerUpdate: "Update Banner",
    bannerDeleteConfirm: "Hapus Banner?",
    uploadImage: "Klik untuk upload gambar",
    // Menu
    addMenu: "Tambah Menu",
    editMenu: "Edit Menu",
    menuTitle: "Manajemen Menu",
    menuSubtitle: "Kelola menu navigasi dinamis",
    menuNameField: "Nama Menu",
    menuLocation: "Lokasi",
    menuLocationHeader: "Header",
    menuLocationFooter: "Footer",
    menuLocationMobile: "Mobile",
    menuIsActive: "Aktif",
    menuSaved: "Menu disimpan",
    menuItemSaved: "Menu item disimpan",
    menuDeleted: "Menu dihapus",
    menuItemDeleted: "Item dihapus",
    menuNoItems: "Belum ada item menu",
    menuNoMenus: "Belum ada menu",
    menuItemTitle: "Judul",
    menuItemType: "Tipe",
    menuItemValue: "Value (URL/Route)",
    menuItemContent: "Konten Halaman",
    menuItemNeedsAuth: "Butuh Login",
    menuItemTypeRoute: "Route",
    menuItemTypeUrl: "URL",
    menuItemTypePage: "Halaman",
    menuItemTypeNews: "Berita",
    menuDeleteConfirm: "Hapus Menu?",
    menuDeleteDesc: "Menu akan dihapus.",
    addItem: "Tambah Item",
    editItem: "Edit Item",
    // Documents
    addDocument: "Tambah Dokumen",
    editDocument: "Edit Dokumen",
    documentTitle: "Manajemen Dokumen PPID",
    documentSubtitle: "Kelola dokumen PPID",
    docTitleField: "Judul Dokumen",
    docNumber: "Nomor Dokumen",
    docKind: "Jenis Dokumen",
    docCategory: "Kategori Dokumen",
    docTypeField: "Tipe/Format File",
    docContent: "Konten Dokumen",
    docContentDesc: "Konten opsional. Bisa diisi dengan ringkasan atau penjelasan dokumen.",
    docStatus: "Status",
    docPublishedAt: "Tanggal Publikasi",
    docPublisher: "Publisher",
    docFile: "Upload File",
    docCurrentFile: "File saat ini",
    docSaved: "Dokumen disimpan",
    docDeleted: "Dokumen dihapus",
    docRestored: "Dokumen dipulihkan",
    docNotFound: "Belum ada dokumen",
    docInTrash: "Tidak ada dokumen di trash",
    docJenis: "Jenis",
    docKategori: "Kategori",
    docTipe: "Tipe",
    docTanggalPublikasi: "Tanggal Publikasi",
    docSaveBtn: "Simpan Dokumen",
    docDeleteConfirm: "Hapus Dokumen?",
    docDeleteDesc: "akan dipindahkan ke trash.",
    docSelectKind: "Pilih jenis...",
    docSelectCategory: "Pilih kategori...",
    docSelectType: "Pilih tipe file...",
    allKinds: "Semua Jenis",
    allCategories: "Semua Kategori",
    searchDoc: "Cari dokumen...",
    // User management
    addUser: "Tambah User",
    editUser: "Edit User",
    userTitle: "Manajemen User",
    userSubtitle: "Kelola akun admin sistem",
    // Permits
    permitTitle: "Manajemen Izin Penelitian",
    permitSubtitle: "Kelola pengajuan izin penelitian",
    // Surveys
    surveyTitle: "Survei IKM",
    surveySubtitle: "Survei Indeks Kepuasan Masyarakat",
    totalResponden: "Total Responden",
    avgIKM: "Rata-rata IKM",
    surveyNoData: "Belum ada data survei",
    surveyName: "Nama Responden",
    surveyAge: "Usia",
    surveyGender: "Jenis Kelamin",
    surveyDate: "Tanggal",
    surveyIKM: "Nilai IKM",
    // Reports
    reportTitle: "Laporan Akhir",
    // Suggestions
    suggestionTitle: "Kotak Saran",
    suggestionSubtitle: "Pesan masuk dari masyarakat",
    suggestionSender: "Pengirim",
    suggestionMessage: "Pesan",
    suggestionAnon: "Anonim",
    suggestionNoData: "Belum ada saran masuk",
    // Letter templates
    templateTitle: "Template Surat",
    templateSubtitle: "Kelola template surat izin penelitian",
    addTemplate: "Tambah Template",
    editTemplate: "Edit Template",
    viewDetails: "Lihat Detail",
    updateStatus: "Ubah Status",
    generateLetter: "Generate Surat",
    requestNumber: "Nomor Pengajuan",
    applicantName: "Nama Pemohon",
    researchTitle: "Judul Penelitian",
    researchLocation: "Lokasi Penelitian",
    submittedAt: "Tanggal Pengajuan",
    accessLevel: "Level Akses",
    publishYear: "Tahun Terbit",
    documentNumber: "Nomor Dokumen",
    placement: "Penempatan",
    location: "Lokasi",
    allRoles: "Semua Role",
    superAdmin: "Super Admin",
    adminBPP: "Admin BAPPEDA",
    adminRIDA: "Admin RIDA",
    filterAll: "Semua",
    filterStatus: "Filter Status",
    filterCategory: "Filter Kategori",
    noNewsFound: "Tidak ada berita ditemukan",
    noPermitFound: "Tidak ada izin penelitian ditemukan",
    noUserFound: "Tidak ada user ditemukan",
    tableColTitle: "Judul",
    tableColAuthor: "Penulis",
    tableColStatus: "Status",
    tableColDate: "Tanggal",
    tableColAction: "Aksi",
    tableColName: "Nama",
    tableColRole: "Role",
    tableColNumber: "Nomor",
    tableColApplicant: "Pemohon",
    // Survey aliases
    totalRespondents: "Total Responden",
    surveyRespondent: "Responden",
    surveyScore: "Skor IKM",
    surveyEducation: "Pendidikan",
    // Suggestion aliases
    suggestionIncoming: "Saran masuk",
    // Login aliases
    loginTitle: "Masuk ke Sistem",
    loginDescription: "Gunakan akun admin yang telah diberikan",
    loginUsername: "Username / Email",
    loginPassword: "Password",
    loginProcessing: "Memproses...",
    loginSubmit: "Masuk",
    // Theme
    darkMode: "Mode Gelap",
    lightMode: "Mode Terang",
    toggleTheme: "Ganti Tema",
    // Notifications
    notifications: "Notifikasi",
    markAllRead: "Tandai semua dibaca",
    noNotifications: "Tidak ada notifikasi",
    justNow: "Baru saja",
    minutesAgo: "menit lalu",
    hoursAgo: "jam lalu",
    unreadNotifications: "belum dibaca",
    allRead: "Semua sudah dibaca",
    // PPID Sidebar
    daftarDokumen: "Daftar Dokumen",
    layananInformasi: "Layanan Informasi",
    permohonanInformasi: "Permohonan Informasi",
    keberatan: "Keberatan",
    ppidSection: "PPID",
    // Access denied
    accessDenied: "Akses Ditolak",
    accessDeniedDesc: "Anda tidak memiliki izin untuk mengakses halaman ini.",
    // Push Notification
    pushNotification: "Push Notifikasi",
    pushNotifTitle: "Kirim Push Notifikasi",
    pushNotifSubtitle: "Kirim notifikasi ke semua pengguna sistem",
    inAppNotif: "Notifikasi In-App",
    notifTitle: "Judul Notifikasi",
    notifTitlePlaceholder: "Contoh: Pengumuman Penting",
    notifMessage: "Pesan Notifikasi",
    notifMessagePlaceholder: "Tulis isi pesan notifikasi di sini...",
    sendNotif: "Kirim Notifikasi",
    sending: "Mengirim...",
    notifSent: "Notifikasi terkirim!",
    notifSentDesc: "Notifikasi berhasil dikirim ke semua pengguna",
    notifTargetAll: "Kirim ke Semua Pengguna",
    notifTargetAllDesc: "Notifikasi akan diterima oleh seluruh admin yang terdaftar di sistem",
    // Change Password
    changePassword: "Ganti Password",
    currentPassword: "Password Lama",
    newPassword: "Password Baru",
    confirmPassword: "Konfirmasi Password Baru",
    passwordChanged: "Password berhasil diubah",
    passwordMismatch: "Password baru tidak cocok",
    passwordWrong: "Password lama salah",
    changePasswordBtn: "Ganti Password",
    // Document Requests
    documentRequests: "Permohonan Dokumen",
    docReqTitle: "Permohonan Dokumen",
    docReqSubtitle: "Daftar pemohon yang mengunduh dokumen",
    docReqSearchPlaceholder: "Cari nama, email, atau no HP...",
    docReqTotalRequesters: "pemohon",
    docReqNoData: "Tidak ada data permohonan",
    docReqDeleteAll: "Hapus Semua Permohonan",
    docReqDeleteAllDesc: "Apakah Anda yakin ingin menghapus semua permohonan dokumen dari",
    docReqDeleteAllSuccess: "Semua permohonan dokumen pemohon dihapus",
    docReqDetailTitle: "Detail Permohonan Dokumen",
    docReqDetailSubtitle: "Dokumen yang diunduh oleh pemohon",
    docReqApplicantData: "Data Pemohon",
    docReqFullName: "Nama Lengkap",
    docReqDocumentsList: "Dokumen yang Diunduh",
    docReqDocumentName: "Nama Dokumen",
    docReqKind: "Jenis",
    docReqCategory: "Kategori",
    docReqType: "Tipe",
    docReqFile: "File",
    docReqViewFile: "Lihat File",
    docReqNoDocuments: "Tidak ada data dokumen",
    docReqDocumentCount: "dokumen",
    docReqDeleteDoc: "Hapus Permohonan",
    docReqDeleteDocDesc: "Apakah Anda yakin ingin menghapus permohonan dokumen",
    docReqDeleteSuccess: "Permohonan dokumen dihapus",
    requestPurpose: "Tujuan Permohonan",
    informationDetail: "Detail Informasi yang Diminta",
    docResponseFile: "File Jawaban",
    viewFile: "Lihat File",
    // Error messages
    errorFetchData: "Gagal mengambil data",
    errorSaveData: "Gagal menyimpan data",
    errorDeleteData: "Gagal menghapus data",
    errorUpdateData: "Gagal memperbarui data",
    errorUpload: "Gagal mengunggah file",
    // Export labels
    exportApplicants: "Pemohon",
  },
  en: {
    // Navigation
    dashboard: "Dashboard",
    news: "News",
    categories: "News Categories",
    banners: "Banners",
    menus: "Menus",
    documents: "Documents",
    docKinds: "Document Kinds",
    docCategories: "Document Categories",
    docTypes: "File Types",
    permits: "Research Permits",
    surveys: "IKM Survey",
    reports: "Final Reports",
    suggestions: "Suggestions Box",
    templates: "Letter Templates",
    users: "User Management",
    bappeda: "BAPPEDA",
    rida: "RIDA",
    administration: "Administration",
    general: "General",
    // Auth
    logout: "Sign Out",
    logoutConfirm: "Are you sure you want to sign out?",
    logoutTitle: "Confirm Sign Out",
    portal: "BAPPERIDA Kalteng Admin Portal",
    signIn: "Sign In to System",
    signInDesc: "Use your admin account credentials",
    usernameLabel: "Username / Email",
    passwordLabel: "Password",
    loginBtn: "Sign In",
    loggingIn: "Signing in...",
    // Common
    cancel: "Cancel",
    confirm: "Yes, Sign Out",
    save: "Save",
    saving: "Saving...",
    edit: "Edit",
    delete: "Delete",
    add: "Add",
    search: "Search",
    name: "Name",
    action: "Action",
    status: "Status",
    active: "Active",
    inactive: "Inactive",
    draft: "Draft",
    published: "Published",
    trash: "Trash",
    restore: "Restore",
    previous: "Previous",
    next: "Next",
    page: "Page",
    of: "of",
    loading: "Loading...",
    noData: "No data found",
    confirmDelete: "Confirm Delete",
    confirmDeleteDesc: "Are you sure you want to delete this item? This action cannot be undone.",
    create: "Create",
    update: "Update",
    close: "Close",
    back: "Back",
    preview: "Preview",
    download: "Download",
    generate: "Generate",
    title: "Title",
    description: "Description",
    content: "Content",
    date: "Date",
    category: "Category",
    type: "Type",
    file: "File",
    image: "Image",
    role: "Role",
    username: "Username",
    password: "Password",
    email: "Email",
    phone: "Phone",
    address: "Address",
    institution: "Institution",
    totalData: "Total records",
    searchPlaceholder: "Search...",
    enterTrash: "Enter Trash",
    exitTrash: "Exit Trash",
    // Dashboard
    welcomeBack: "Welcome back",
    totalNews: "Total News",
    publishedNews: "published",
    draftNews: "Draft News",
    trashNews: "News Trash",
    activeBanners: "Active Banners",
    ppidDocs: "PPID Documents",
    researchPermits: "Research Permits",
    waitingReview: "waiting review",
    pendingReview: "Pending Review",
    ikmSurvey: "IKM Survey",
    avgSatisfaction: "Avg. Satisfaction",
    newsDocTab: "News & Documents",
    permitTab: "Research Permits",
    surveyTab: "Survey Satisfaction",
    failedStats: "Failed to load statistics",
    fromLastMonth: "from last month",
    // News
    addNews: "Add News",
    editNews: "Edit News",
    newsTitle: "News Management",
    newsSubtitle: "Manage BAPPERIDA news and articles",
    addCategory: "Add Category",
    editCategory: "Edit Category",
    categoryTitle: "News Categories",
    // Banner
    addBanner: "Add Banner",
    editBanner: "Edit Banner",
    bannerTitle: "Banner Management",
    bannerSubtitle: "Manage banners and portal ads",
    bannerTitleField: "Banner Title",
    bannerAltText: "Alt Text (accessibility)",
    bannerAltDesc: "Image description for screen readers...",
    bannerPlacement: "Placement",
    bannerPlacementHome: "Home",
    bannerPlacementNews: "News",
    bannerPlacementSidebar: "Sidebar",
    bannerPlacementPopup: "Popup",
    bannerLinkType: "Link Type",
    bannerLinkTypeExt: "External URL",
    bannerLinkTypePage: "Internal Page",
    bannerLinkTypeNews: "News",
    bannerLinkUrl: "Link URL",
    bannerDesktop: "Desktop Image",
    bannerMobile: "Mobile Image",
    bannerStartAt: "Start Date",
    bannerEndAt: "End Date",
    bannerActivate: "Activate Banner",
    bannerActivateDesc: "Active banners will appear on the public portal",
    bannerViews: "Views",
    bannerClicks: "Clicks",
    bannerStatus: "Status",
    bannerGambar: "Image",
    bannerJudulPlacement: "Title & Placement",
    bannerNotFound: "No banners found",
    bannerInTrash: "No banners in trash",
    bannerDeleted: "Banner deleted",
    bannerUpdated: "Banner updated",
    bannerCreated: "Banner created",
    bannerSave: "Save Banner",
    bannerUpdate: "Update Banner",
    bannerDeleteConfirm: "Delete Banner?",
    uploadImage: "Click to upload image",
    // Menu
    addMenu: "Add Menu",
    editMenu: "Edit Menu",
    menuTitle: "Menu Management",
    menuSubtitle: "Manage dynamic navigation menus",
    menuNameField: "Menu Name",
    menuLocation: "Location",
    menuLocationHeader: "Header",
    menuLocationFooter: "Footer",
    menuLocationMobile: "Mobile",
    menuIsActive: "Active",
    menuSaved: "Menu saved",
    menuItemSaved: "Menu item saved",
    menuDeleted: "Menu deleted",
    menuItemDeleted: "Item deleted",
    menuNoItems: "No menu items yet",
    menuNoMenus: "No menus yet",
    menuItemTitle: "Title",
    menuItemType: "Type",
    menuItemValue: "Value (URL/Route)",
    menuItemContent: "Page Content",
    menuItemNeedsAuth: "Requires Login",
    menuItemTypeRoute: "Route",
    menuItemTypeUrl: "URL",
    menuItemTypePage: "Page",
    menuItemTypeNews: "News",
    menuDeleteConfirm: "Delete Menu?",
    menuDeleteDesc: "Menu will be deleted.",
    addItem: "Add Item",
    editItem: "Edit Item",
    // Documents
    addDocument: "Add Document",
    editDocument: "Edit Document",
    documentTitle: "PPID Document Management",
    documentSubtitle: "Manage PPID documents",
    docTitleField: "Document Title",
    docNumber: "Document Number",
    docKind: "Document Kind",
    docCategory: "Document Category",
    docTypeField: "File Type/Format",
    docContent: "Document Content",
    docContentDesc: "Optional content. Can be a summary or description of the document.",
    docStatus: "Status",
    docPublishedAt: "Publication Date",
    docPublisher: "Publisher",
    docFile: "Upload File",
    docCurrentFile: "Current file",
    docSaved: "Document saved",
    docDeleted: "Document deleted",
    docRestored: "Document restored",
    docNotFound: "No documents found",
    docInTrash: "No documents in trash",
    docJenis: "Kind",
    docKategori: "Category",
    docTipe: "Type",
    docTanggalPublikasi: "Publication Date",
    docSaveBtn: "Save Document",
    docDeleteConfirm: "Delete Document?",
    docDeleteDesc: "will be moved to trash.",
    docSelectKind: "Select kind...",
    docSelectCategory: "Select category...",
    docSelectType: "Select file type...",
    allKinds: "All Kinds",
    allCategories: "All Categories",
    searchDoc: "Search documents...",
    // User management
    addUser: "Add User",
    editUser: "Edit User",
    userTitle: "User Management",
    userSubtitle: "Manage admin system accounts",
    // Permits
    permitTitle: "Research Permit Management",
    permitSubtitle: "Manage research permit submissions",
    // Surveys
    surveyTitle: "IKM Survey",
    surveySubtitle: "Community Satisfaction Index Survey",
    totalResponden: "Total Respondents",
    avgIKM: "Avg. IKM Score",
    surveyNoData: "No survey data yet",
    surveyName: "Respondent Name",
    surveyAge: "Age",
    surveyGender: "Gender",
    surveyDate: "Date",
    surveyIKM: "IKM Score",
    // Reports
    reportTitle: "Final Reports",
    // Suggestions
    suggestionTitle: "Suggestions Box",
    suggestionSubtitle: "Messages from the public",
    suggestionSender: "Sender",
    suggestionMessage: "Message",
    suggestionAnon: "Anonymous",
    suggestionNoData: "No suggestions yet",
    // Letter templates
    templateTitle: "Letter Templates",
    templateSubtitle: "Manage research permit letter templates",
    addTemplate: "Add Template",
    editTemplate: "Edit Template",
    viewDetails: "View Details",
    updateStatus: "Update Status",
    generateLetter: "Generate Letter",
    requestNumber: "Request Number",
    applicantName: "Applicant Name",
    researchTitle: "Research Title",
    researchLocation: "Research Location",
    submittedAt: "Submitted At",
    accessLevel: "Access Level",
    publishYear: "Publish Year",
    documentNumber: "Document Number",
    placement: "Placement",
    location: "Location",
    allRoles: "All Roles",
    superAdmin: "Super Admin",
    adminBPP: "Admin BAPPEDA",
    adminRIDA: "Admin RIDA",
    filterAll: "All",
    filterStatus: "Filter Status",
    filterCategory: "Filter Category",
    noNewsFound: "No news found",
    noPermitFound: "No research permit found",
    noUserFound: "No user found",
    tableColTitle: "Title",
    tableColAuthor: "Author",
    tableColStatus: "Status",
    tableColDate: "Date",
    tableColAction: "Action",
    tableColName: "Name",
    tableColRole: "Role",
    tableColNumber: "Number",
    tableColApplicant: "Applicant",
    // Survey aliases
    totalRespondents: "Total Respondents",
    surveyRespondent: "Respondent",
    surveyScore: "IKM Score",
    surveyEducation: "Education",
    // Suggestion aliases
    suggestionIncoming: "Incoming suggestions",
    // Login aliases
    loginTitle: "Sign In to System",
    loginDescription: "Use your admin account credentials",
    loginUsername: "Username / Email",
    loginPassword: "Password",
    loginProcessing: "Signing in...",
    loginSubmit: "Sign In",
    // Theme
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    toggleTheme: "Toggle Theme",
    // Notifications
    notifications: "Notifications",
    markAllRead: "Mark all as read",
    noNotifications: "No notifications",
    justNow: "Just now",
    minutesAgo: "minutes ago",
    hoursAgo: "hours ago",
    unreadNotifications: "unread",
    allRead: "All caught up",
    // PPID Sidebar
    daftarDokumen: "Document List",
    layananInformasi: "Information Services",
    permohonanInformasi: "Information Requests",
    keberatan: "Objections",
    ppidSection: "PPID",
    // Access denied
    accessDenied: "Access Denied",
    accessDeniedDesc: "You do not have permission to access this page.",
    // Push Notification
    pushNotification: "Push Notification",
    pushNotifTitle: "Send Push Notification",
    pushNotifSubtitle: "Send a notification to all system users",
    inAppNotif: "In-App Notification",
    notifTitle: "Notification Title",
    notifTitlePlaceholder: "e.g. Important Announcement",
    notifMessage: "Notification Message",
    notifMessagePlaceholder: "Write the notification message here...",
    sendNotif: "Send Notification",
    sending: "Sending...",
    notifSent: "Notification sent!",
    notifSentDesc: "Notification successfully sent to all users",
    notifTargetAll: "Send to All Users",
    notifTargetAllDesc: "Notification will be received by all registered admins in the system",
    // Change Password
    changePassword: "Change Password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmPassword: "Confirm New Password",
    passwordChanged: "Password changed successfully",
    passwordMismatch: "New passwords do not match",
    passwordWrong: "Current password is incorrect",
    changePasswordBtn: "Change Password",
    // Document Requests
    documentRequests: "Document Requests",
    docReqTitle: "Document Requests",
    docReqSubtitle: "List of users who downloaded documents",
    docReqSearchPlaceholder: "Search by name, email, or phone...",
    docReqTotalRequesters: "requesters",
    docReqNoData: "No request data",
    docReqDeleteAll: "Delete All Requests",
    docReqDeleteAllDesc: "Are you sure you want to delete all document requests from",
    docReqDeleteAllSuccess: "All document requests for this user deleted",
    docReqDetailTitle: "Document Request Detail",
    docReqDetailSubtitle: "Documents downloaded by this user",
    docReqApplicantData: "Applicant Data",
    docReqFullName: "Full Name",
    docReqDocumentsList: "Downloaded Documents",
    docReqDocumentName: "Document Name",
    docReqKind: "Kind",
    docReqCategory: "Category",
    docReqType: "Type",
    docReqFile: "File",
    docReqViewFile: "View File",
    docReqNoDocuments: "No documents found",
    docReqDocumentCount: "documents",
    docReqDeleteDoc: "Delete Request",
    docReqDeleteDocDesc: "Are you sure you want to delete the document request",
    docReqDeleteSuccess: "Document request deleted",
    requestPurpose: "Request Purpose",
    informationDetail: "Information Detail Requested",
    docResponseFile: "Response File",
    viewFile: "View File",
    // Error messages
    errorFetchData: "Failed to fetch data",
    errorSaveData: "Failed to save data",
    errorDeleteData: "Failed to delete data",
    errorUpdateData: "Failed to update data",
    errorUpload: "Failed to upload file",
    // Export labels
    exportApplicants: "Applicants",
  },
};

interface LangCtx {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const LangContext = createContext<LangCtx | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => (localStorage.getItem("lang") as Lang) || "id");

  const setLang = (l: Lang) => {
    localStorage.setItem("lang", l);
    setLangState(l);
  };

  const t = (key: string) => translations[lang][key] || key;

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be inside LanguageProvider");
  return ctx;
}
